export interface OrderInterface {
  id: string;
  // 用户ID
  userId: string;
  user: string;
  // 用户ID
  bossId: string;
  bossInfo: any;
  // 球场ID
  stadiumId: string;
  // 场地ID
  spaceId: string;
  // 场次ID
  matchId: string;
  payMethod: number;
  // 支付金额
  payAmount: number;
  newMonthlyCard: boolean;
  // 是否月卡
  isMonthlyCard: boolean;
  // 人数
  personCount: number;
  // 状态
  status: number;
  refundType: number;
  payAt: number;
  refundAt: number;
  refundId: string;
  refundAmount: number;
  createdAt: number;
  updatedAt: number;
  wxOrderId: string;
  wxRefundId: string;
  prepayInfo: any;
  closeFlag: boolean;
  isCompensate: boolean;
  compensateAmt: number;
}
